name: total_image_compress
description: A Flutter package for fast image compression
version: 0.0.1
homepage: https://github.com/DaPotatoMan/total_image_compress

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.0.0"

dependencies:
  fast_image_compress: ^0.0.3
  flutter:
    sdk: flutter
  image: ">=4.0.0 <5.0.0"
  web: ">=1.0.0"

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/core.mjs
    - assets/worker.mjs
